### ISSUE TITLE
Session data appears to be absent after about less than 1 hour of inactivity

### ISSUE THREAD

**Issue by brlafreniere** [brlafreniere/vue-chat-app#5]
After about, maybe 30 minutes or so, it appears this session data is gone, and then errors begin to appear.

The app uses Redis as a session store, so perhaps the issue is with Redis.

```
var ExpressSession = require('express-session');
var RedisStore = require('connect-redis')(ExpressSession);

expires_in_x_days = 5;
expiration_date = new Date();
expiration_date.setDate(expiration_date.getDate() + expires_in_x_days);

var session = ExpressSession({
    resave: true,
    saveUninitialized: true,
    store: new RedisStore(),
    secret: process.env.SESSION_SECRET_KEY,
    cookie: {
        expires: expiration_date
    }
});

module.exports = session;
```

```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'id' of undefined
    at Socket.socket.on (/home/ubuntu/chat-app/backend/lib/socket-io/event-handlers.js:24:80)
    at Socket.emit (events.js:189:13)
    at Socket.emit (/home/ubuntu/chat-app/backend/node_modules/socket.io/lib/socket.js:142:10)
    at Socket.onclose (/home/ubuntu/chat-app/backend/node_modules/socket.io/lib/socket.js:454:8)
    at Client.onclose (/home/ubuntu/chat-app/backend/node_modules/socket.io/lib/client.js:254:24)
    at Socket.emit (events.js:194:15)
    at Socket.onClose (/home/ubuntu/chat-app/backend/node_modules/engine.io/lib/socket.js:318:10)
    at Object.onceWrapper (events.js:277:13)
    at WebSocket.emit (events.js:189:13)
    at WebSocket.Transport.onClose (/home/ubuntu/chat-app/backend/node_modules/engine.io/lib/transport.js:127:8)
(node:13703) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13703) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by brlafreniere** [comment]
Possibly related: https://github.com/oskosk/express-socket.io-session/issues/6

**Comment by brlafreniere** [comment]
no longer relevant... using rails now
